require 'smartcore/requests/base_request'
require 'smartcore/requests/client_auth_requests/client_sign_in_request'
require 'smartcore/requests/client_auth_requests/client_sign_out_request'
require 'smartcore/requests/information_requests/check_email_presence_request'